### ISSUE TITLE
html form 엘리먼트는 상위 폰트를 상속받지 않는다.

### ISSUE THREAD

**Issue by eunbin20** [eunbin20/til#1]
An element inherits a property only when no style sheet sets that property on the element (or when the value `inherit`
 has been set). Form fields generally have settings for them in browser style sheets.

 요소는 해당 속성을 지정하는 스타일 시트가 없거나 `inherit`으로 설정되어있는 경우에만 상위 속성을 상속받는다. Form 필드들은 일반적으로 브라우저가 해당 요소에 대한 스타일 시트를 가지고있어 속성값을 `inherit`으로 설정해주지 않는 한 상위 속성을 상속받지 않는다. 

- html
```html
<body>
  <button>버튼</button>
  <div>division</div>
</body>
```

- css
```css
body {
  font-family: 'Apple SD Gothic Neo';
  font-weight: 700;
  color: red;
}
```

### Result

<img width="250" alt="스크린샷 2022-12-20 오후 3 31 15" src="https://user-images.githubusercontent.com/43979066/208599128-fb31f5f5-90e8-46e5-94df-32ce7d5f4f4b.png">
